---
name: "🔄 Rclone"
on:
  push:
    paths:
      - "**.svg"
      - "**.png"
  workflow_dispatch:
    inputs:
      debug:
        description: "Dry-run"
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    if: github.repository == 'digital-clouds/dashboard-icons'
    runs-on: ubuntu-latest
    env:
      svg_local: "svg"
      svg_remote: "r2:images/icons/svg"
      png_local: "png"
      png_remote: "r2:images/icons/png"
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@v4
      - if: github.event
        name: "⏫ Sync SVG"
        uses: z-shell/.github/actions/rclone@main
        with:
          config: ${{ secrets.R2_RCLONE_CONFIG }}
          args: "sync -u ${{ env.svg_local }} ${{ env.svg_remote }}"
          debug: ${{ inputs.debug }}
      - name: "⏫ Sync PNG"
        uses: z-shell/.github/actions/rclone@main
        with:
          config: ${{ secrets.R2_RCLONE_CONFIG }}
          args: "sync -u ${{ env.png_local }} ${{ env.png_remote }}"
          debug: ${{ inputs.debug }}
